# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/8_5/8_5.srcs/sources_1/ip/vp_bin_c_0/vp_bin_c_0.xci
# IP: The module: 'vp_bin_c_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/8_5/8_5.srcs/sources_1/ip/vp_bin_c_0/src/LUT_bin/LUT_bin.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LUT_bin || ORIG_REF_NAME==LUT_bin} -quiet] -quiet

# XDC: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/8_5/8_5.srcs/sources_1/ip/vp_bin_c_0/src/LUT_bin/LUT_bin_ooc.xdc

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/8_5/8_5.srcs/sources_1/ip/vp_bin_c_0/vp_bin_c_0.xci
# IP: The module: 'vp_bin_c_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/8_5/8_5.srcs/sources_1/ip/vp_bin_c_0/src/LUT_bin/LUT_bin.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LUT_bin || ORIG_REF_NAME==LUT_bin} -quiet] -quiet

# XDC: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/8_5/8_5.srcs/sources_1/ip/vp_bin_c_0/src/LUT_bin/LUT_bin_ooc.xdc
