`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 03/25/2018 06:53:56 PM
// Design Name: 
// Module Name: verify
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module verify
    (
        input [9:0] in,
        input or_gate_out
    );
    
    integer i, j, file;
    reg or_bit = 1'b0;
    
    initial
    begin
//        file = $fopen("C:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_3/Or_gate/log.txt", "wb");
        file = $fopen("/home/lsriw/sr/StyczenBartlomiej/Reconfigurable-Systems-Laboratory-Class/Lab_3/Or_gate/log.txt", "wb");
        for (i = 0; i < 1024; i=i+1) begin
            #2; // wait 1 clock cycle
            for (j = 0; j < 10; j=j+1) begin
                or_bit = or_bit | in[j];
            end

            if (or_bit != or_gate_out) begin
                $fwrite(file, "ERROR: Incorrect output generated by input: %d\n", in);
            end
        end 
        $fclose(file);
    end
    
endmodule
