# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/LUT_bin/LUT_bin.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LUT_bin || ORIG_REF_NAME==LUT_bin} -quiet] -quiet
