# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hdmi_vga_zybo_src/Zybo_HDMI.xdc

# Block Designs: bd/hdmi_vga/hdmi_vga.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga || ORIG_REF_NAME==hdmi_vga} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_vga_clk_wiz_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_xlconstant_0_0/hdmi_vga_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_xlconstant_0_0 || ORIG_REF_NAME==hdmi_vga_xlconstant_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_xlconstant_0_1/hdmi_vga_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_xlconstant_0_1 || ORIG_REF_NAME==hdmi_vga_xlconstant_0_1} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_rgb2vga_1_0/hdmi_vga_rgb2vga_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_rgb2vga_1_0 || ORIG_REF_NAME==hdmi_vga_rgb2vga_1_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_dvi2rgb_1_1/hdmi_vga_dvi2rgb_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_dvi2rgb_1_1 || ORIG_REF_NAME==hdmi_vga_dvi2rgb_1_1} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vp_0_0 || ORIG_REF_NAME==hdmi_vga_vp_0_0} -quiet] -quiet

# XDC: bd/hdmi_vga/hdmi_vga_ooc.xdc
