# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/sr/StyczenBartlomiej/Reconfigurable-Systems-Laboratory-Class/11/1/centroid/centroid.srcs/sources_1/ip/accum/accum.xci
# IP: The module: 'accum' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/sr/StyczenBartlomiej/Reconfigurable-Systems-Laboratory-Class/11/1/centroid/centroid.srcs/sources_1/ip/accum/accum_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accum'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lsriw/sr/StyczenBartlomiej/Reconfigurable-Systems-Laboratory-Class/11/1/centroid/centroid.srcs/sources_1/ip/accum/accum.xci
# IP: The module: 'accum' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/sr/StyczenBartlomiej/Reconfigurable-Systems-Laboratory-Class/11/1/centroid/centroid.srcs/sources_1/ip/accum/accum_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accum'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
