# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/delayLineBRAM/delayLineBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# XDC: ip/delayLineBRAM/delayLineBRAM_ooc.xdc
