# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/median5x5_0/median5x5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==median5x5_0 || ORIG_REF_NAME==median5x5_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/median5x5_0/src/delayLineBRAM/delayLineBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/rgb2ycbcr_0_2/rgb2ycbcr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/rgb2ycbcr_0_2/src/mult_gen_1/mult_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/rgb2ycbcr_0_2/src/c_addsub_1/c_addsub_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_1 || ORIG_REF_NAME==c_addsub_1} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0_1/centroid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==centroid_0 || ORIG_REF_NAME==centroid_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0_1/src/divider_32_20_0/divider_32_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0_1/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0_1/src/c_accum_0/c_accum_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_accum_0 || ORIG_REF_NAME==c_accum_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_centroid_0_3/vis_centroid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vis_centroid_0 || ORIG_REF_NAME==vis_centroid_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_6/vis_circle_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vis_circle_0 || ORIG_REF_NAME==vis_circle_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_6/src/result/result.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==result || ORIG_REF_NAME==result} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_6/src/sum/sum.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum || ORIG_REF_NAME==sum} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_6/src/mult/mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult || ORIG_REF_NAME==mult} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/bounding_box_0_1/bounding_box_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bounding_box_0 || ORIG_REF_NAME==bounding_box_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_bounding_box_0_1/vis_bounding_box_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vis_bounding_box_0 || ORIG_REF_NAME==vis_bounding_box_0} -quiet] -quiet

# XDC: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/median5x5_0/src/delayLineBRAM/delayLineBRAM_ooc.xdc

# IP: C:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/median5x5_0/median5x5_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==median5x5_0 || ORIG_REF_NAME==median5x5_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/median5x5_0/src/delayLineBRAM/delayLineBRAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/rgb2ycbcr_0_2/rgb2ycbcr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/rgb2ycbcr_0_2/src/mult_gen_1/mult_gen_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/rgb2ycbcr_0_2/src/c_addsub_1/c_addsub_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_1 || ORIG_REF_NAME==c_addsub_1} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0_1/centroid_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==centroid_0 || ORIG_REF_NAME==centroid_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0_1/src/divider_32_20_0/divider_32_20_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0_1/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0_1/src/c_accum_0/c_accum_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_accum_0 || ORIG_REF_NAME==c_accum_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_centroid_0_3/vis_centroid_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vis_centroid_0 || ORIG_REF_NAME==vis_centroid_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_6/vis_circle_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vis_circle_0 || ORIG_REF_NAME==vis_circle_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_6/src/result/result.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==result || ORIG_REF_NAME==result} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_6/src/sum/sum.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum || ORIG_REF_NAME==sum} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_6/src/mult/mult.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult || ORIG_REF_NAME==mult} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/bounding_box_0_1/bounding_box_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bounding_box_0 || ORIG_REF_NAME==bounding_box_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_bounding_box_0_1/vis_bounding_box_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vis_bounding_box_0 || ORIG_REF_NAME==vis_bounding_box_0} -quiet] -quiet

# XDC: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/median5x5_0/src/delayLineBRAM/delayLineBRAM_ooc.xdc
