# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hdmi_vga_zybo_src/Zybo_HDMI.xdc

# Block Designs: bd/hdmi_vga/hdmi_vga.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga || ORIG_REF_NAME==hdmi_vga} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_vga_clk_wiz_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_xlconstant_0_0/hdmi_vga_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_xlconstant_0_0 || ORIG_REF_NAME==hdmi_vga_xlconstant_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_xlconstant_0_1/hdmi_vga_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_xlconstant_0_1 || ORIG_REF_NAME==hdmi_vga_xlconstant_0_1} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_rgb2vga_1_0/hdmi_vga_rgb2vga_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_rgb2vga_1_0 || ORIG_REF_NAME==hdmi_vga_rgb2vga_1_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_dvi2rgb_1_1/hdmi_vga_dvi2rgb_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_dvi2rgb_1_1 || ORIG_REF_NAME==hdmi_vga_dvi2rgb_1_1} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vp_0_0 || ORIG_REF_NAME==hdmi_vga_vp_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_bounding_box_0/vis_bounding_box_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vis_bounding_box_0 || ORIG_REF_NAME==vis_bounding_box_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/bounding_box_0/bounding_box_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bounding_box_0 || ORIG_REF_NAME==bounding_box_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/median5x5_0/median5x5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==median5x5_0 || ORIG_REF_NAME==median5x5_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/median5x5_0/src/delayLineBRAM/delayLineBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/rgb2ycbcr_0_1/rgb2ycbcr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/rgb2ycbcr_0_1/src/mult_gen_1/mult_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/rgb2ycbcr_0_1/src/c_addsub_1/c_addsub_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_1 || ORIG_REF_NAME==c_addsub_1} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0/centroid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==centroid_0 || ORIG_REF_NAME==centroid_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0/src/c_accum_0/c_accum_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_accum_0 || ORIG_REF_NAME==c_accum_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0/src/divider_32_20_0/divider_32_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/centroid_0/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_centroid_0_2/vis_centroid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vis_centroid_0 || ORIG_REF_NAME==vis_centroid_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_5/vis_circle_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vis_circle_0 || ORIG_REF_NAME==vis_circle_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_5/src/result/result.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==result || ORIG_REF_NAME==result} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_5/src/sum/sum.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum || ORIG_REF_NAME==sum} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/vis_circle_0_5/src/mult/mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult || ORIG_REF_NAME==mult} -quiet] -quiet

# XDC: bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_vga_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_vga_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_vga_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_vga_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0_ooc.xdc

# XDC: bd/hdmi_vga/ip/hdmi_vga_dvi2rgb_1_1/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_vga_dvi2rgb_1_1 || ORIG_REF_NAME==hdmi_vga_dvi2rgb_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_vga/ip/hdmi_vga_dvi2rgb_1_1/src/dvi2rgb_ooc.xdc

# XDC: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/median5x5_0/src/delayLineBRAM/delayLineBRAM_ooc.xdc

# XDC: bd/hdmi_vga/hdmi_vga_ooc.xdc
