# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/2/vis_circle/vis_circle.srcs/sources_1/ip/mult/mult.xci
# IP: The module: 'mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/2/vis_circle/vis_circle.srcs/sources_1/ip/mult/mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/2/vis_circle/vis_circle.srcs/sources_1/ip/mult/mult.xci
# IP: The module: 'mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/2/vis_circle/vis_circle.srcs/sources_1/ip/mult/mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
