webtalk_init -webtalk_dir C:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/12/1/median5x5/median5x5.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jun 13 13:22:01 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f72f8ee5-afb7-45ac-9cbd-6dc1d06d06e8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7d24be8a2e4f4c6b8dd1e539fb228dfd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "70" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "18.70_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15332_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1923715962 -regid "" -xml C:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/12/1/median5x5/median5x5.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/12/1/median5x5/median5x5.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/12/1/median5x5/median5x5.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
