# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/lut_8_4/lut_8_4.srcs/sources_1/ip/vp_0/vp_0.xci
# IP: The module: 'vp_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/lut_8_4/lut_8_4.srcs/sources_1/ip/vp_0/vp/vp.srcs/sources_1/ip/LUT/LUT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LUT || ORIG_REF_NAME==LUT} -quiet] -quiet

# XDC: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/lut_8_4/lut_8_4.srcs/sources_1/ip/vp_0/vp/vp.srcs/sources_1/ip/LUT/LUT_ooc.xdc

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/lut_8_4/lut_8_4.srcs/sources_1/ip/vp_0/vp_0.xci
# IP: The module: 'vp_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/lut_8_4/lut_8_4.srcs/sources_1/ip/vp_0/vp/vp.srcs/sources_1/ip/LUT/LUT.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LUT || ORIG_REF_NAME==LUT} -quiet] -quiet

# XDC: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/Lab_5/lut_8_4/lut_8_4.srcs/sources_1/ip/vp_0/vp/vp.srcs/sources_1/ip/LUT/LUT_ooc.xdc
