# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/median5x5_0/median5x5_0.xci
# IP: The module: 'median5x5_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/median5x5_0/src/delayLineBRAM/delayLineBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# XDC: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/median5x5_0/src/delayLineBRAM/delayLineBRAM_ooc.xdc

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/median5x5_0/median5x5_0.xci
# IP: The module: 'median5x5_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/median5x5_0/src/delayLineBRAM/delayLineBRAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# XDC: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/median5x5_0/src/delayLineBRAM/delayLineBRAM_ooc.xdc
