# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/10/3/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
# IP: The module: 'rgb2ycbcr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/10/3/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0/src/mult_gen_1/mult_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/10/3/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0/src/c_addsub_1/c_addsub_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_1 || ORIG_REF_NAME==c_addsub_1} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/10/3/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
# IP: The module: 'rgb2ycbcr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/10/3/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0/src/mult_gen_1/mult_gen_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/10/3/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0/src/c_addsub_1/c_addsub_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_1 || ORIG_REF_NAME==c_addsub_1} -quiet] -quiet
