# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/centroid_0/centroid_0.xci
# IP: The module: 'centroid_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/centroid_0/src/divider_32_20_0/divider_32_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/centroid_0/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/centroid_0/src/c_accum_0/c_accum_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_accum_0 || ORIG_REF_NAME==c_accum_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/centroid_0/centroid_0.xci
# IP: The module: 'centroid_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/centroid_0/src/divider_32_20_0/divider_32_20_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/centroid_0/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/11/3/vis_bounding_box/vis_bounding_box.srcs/sources_1/ip/centroid_0/src/c_accum_0/c_accum_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_accum_0 || ORIG_REF_NAME==c_accum_0} -quiet] -quiet
