# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/sr/StyczenBartlomiej/Reconfigurable-Systems-Laboratory-Class/11/1/centroid/centroid.srcs/sources_1/ip/divider_32_20_0/divider_32_20_0.xci
# IP: The module: 'divider_32_20_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/sr/StyczenBartlomiej/Reconfigurable-Systems-Laboratory-Class/11/1/centroid/centroid.srcs/sources_1/ip/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: /home/lsriw/sr/StyczenBartlomiej/Reconfigurable-Systems-Laboratory-Class/11/1/centroid/centroid.srcs/sources_1/ip/divider_32_20_0/divider_32_20_0.xci
# IP: The module: 'divider_32_20_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/sr/StyczenBartlomiej/Reconfigurable-Systems-Laboratory-Class/11/1/centroid/centroid.srcs/sources_1/ip/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet
