# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/My_IPs/vp/src/rgb2ycbcr_0_1/rgb2ycbcr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/My_IPs/vp/src/rgb2ycbcr_0_1/src/mult_gen_1/mult_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1} -quiet] -quiet

# IP: c:/Users/Bartek/Reconfigurable-Systems-Laboratory-Class/My_IPs/vp/src/rgb2ycbcr_0_1/src/c_addsub_1/c_addsub_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_1 || ORIG_REF_NAME==c_addsub_1} -quiet] -quiet
